name: Test run
on: [push, pull_request]

jobs:
  application-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install python3-setuptools
          sudo apt-get install freeglut3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Prepare to run
        run: |
          omz_downloader --name ultra-lightweight-face-detection-rfb-320
          omz_converter --name ultra-lightweight-face-detection-rfb-320 --precisions FP32

      - name: Run application
        run: |
          export DISPLAY=:0
          python3 remote_portrait.py --config config.json
        working-directory: .

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            res.obj
            res.png
            texture.png
            res.mtl
