name: Test run
on: [push, pull_request]

jobs:
  application-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install python3-setuptools
          sudo apt-get install freeglut3-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt

      - name: Prepare to run
        run: |
          omz_downloader --name ultra-lightweight-face-detection-rfb-320
          omz_converter --name ultra-lightweight-face-detection-rfb-320 --precisions FP32

      - name: Run application
        run: |
          export DISPLAY=:0
          python3 remote_portrait.py \
            -i ./test_data/test.png \
            -m_fd ./public/ultra-lightweight-face-detection-rfb-320/FP32/ultra-lightweight-face-detection-rfb-320.xml \
            -m_en ./models_ir/encoder_flame/E_flame.xml \
            -m_flame ./models_ir/flame/flame.xml \
            --template ./resources/head_template.obj \
            -o res.obj \
            --no_show
        working-directory: .

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            res.obj
            res.png
