name: Test run
on: [push, pull_request]

jobs:
  application-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install python3-setuptools
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Run application
        run: |
          python3 remote_portrait.py -h
        working-directory: .

